name: Snapshot

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: ${{ contains(github.event.comment.body, '!snapshot') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create snapshot and comment to PR
        run: pnpx pkg-pr-new publish --comment=update
