name: Publish Approved Pull Requests
on:
  issue_comment:
    types: [created]
  pull_request:
    branches: [master]

jobs:
  approved:
    if: ${{ contains(github.event.comment.body, '!snapshot') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - run: pnpx pkg-pr-new@0.0 publish --compact --comment=create --pnpm --json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
